---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: delete default config of nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: set nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/nginx.conf

- name: apply nginx.config
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
    state: link

- name: restart nginx
  service:
    name: nginx
    state: restarted