name: "Actions for demo branch"

on: #trigger for actions
  push:
    branches:
      - demo

jobs:
#1 step - checkout so ubuntu knows that to work with
  test: #created name -> modules -> parameters
    runs-on: ubuntu-latest


    steps:
      - name: deliver code to a machine
        uses: actions/checkout@v4
      
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: push image on dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          #by default it's false, so we need to specify it
          tags: tiffea/gitea_deployment:latest
          #tags used to separate versions (old, new, stable)
          

